### ISSUE TITLE
Getting example to work

### ISSUE THREAD

**Issue by oleteacher** [Yerikmiller/maricutodb#1]
Hello, your DB looks very promising.

I have downloaded and trying to learn how to use. Looking at the example shortener, have problem to get working.

First, the "short url" copied (by pressing button) results in 404 file not found:

https://xxxxxxxxx.com/testbed/maricutoDB/MaricutoDB/examples/shortener/go/jJAHYiG

Second, if you search for a shortened URL then copy (by pressing button) getting something like this:

https://xxxxxxxxx.com/testbed/maricutoDB/MaricutoDB/examples/shortener/searching.php?query=phpgo/eRy10jT8ze

Any ideas what might be wrong?

As a suggestion, be very useful to have more examples based on your documentation.

Thank you for sharing your DB!

Susan

**Comment by Yerikmiller** [comment]
Hi Susan, firstly the Search Engine had a bug and it was correct, now the result queries will can paginate them. i update the "sorting types" and now the database sort by ascending (a-z | 1-9) and viceversa. I will upload soon.

To fix that error:
Add a ".htaccess" file to "go" folder with the next content:


_RewriteEngine On
RewriteRule ^([a-zA-Z0-9_-]+)$ index.php?url=$1
RewriteRule ^([a-zA-Z0-9_-]+)/$ index.php?url=$1 [L]_


If you want to see the current example working, see the tutorial here
[Creating a URL shortener](http://maricuto.xyz/maricutodb?lang=en&page=creating_a_link_shortener)

Direct download here:
[Download The Example](http://maricuto.xyz/maricutodb/download_shortener)

I don't know if GitHub don't allow upload .htaccess file or if was an upload error.

More examples coming soon...
Thank you.

Maricuto Yorman.

**Comment by oleteacher** [comment]
Thank you Maricuto @Yerikmiller for the update. I will try your new fix or wait for the new upload.

Cheers!

**Comment by Yerikmiller** [comment]
The update is uploaded right now! You can see in the documentation a new feature in "sorting data" and the searching methods has been change a little bit, now you can paginate results for queries.

Thanks for use MaricutoDB
